### ISSUE TITLE
what exactly does the  word ''overridden'' mean here?

### ISSUE THREAD

**Issue by 123yu456** [MCZhi/NGSIM-env#5]
In your paper, the III. METHODOLOGY and D. Environment model
you mentioned, "If the front is the ego vehicle and the gap between them is smaller than the desired gap given by IDM, the environment vehicle will be overridden by IDM and thus not follow its original trajectory anymore. " I cannot understand the meaning of overridden. Can you elaborate that? thanks a lot！

**Comment by 123yu456** [comment]
![20240316180334](https://github.com/MCZhi/Driving-IRL-NGSIM/assets/143694720/c6e6d42b-7010-49e6-a5d3-7318b5f01d0d)
After I run [python dump_data.py D:\\python311\\daima\\Driving-IRL-NGSIM-main\\Next_Generation_Simulation__NGSIM__Vehicle_Trajectories_and_Supporting_Data.csv] 
Although some data was generated, corresponding storage files were not generated. can you tell me the reason? thanks!

**Comment by MCZhi** [comment]
"Override" means that the influenced vehicle will be controlled by an IDM planner instead, deviating from its original trajectory. "dump_data.py" only processes the raw data from the NGSIM data into a more structured format, without saving any data points. It's worth noting that we collect training data from simulations, not offline datasets.

**Comment by 123yu456** [comment]
"Thank you for your response. The issue I'd like to address is that after I ran this command "dump_data.py", the 'processed' folder was not generated, and when I proceeded to the next step, I encountered the following error in the picture. I'm not sure what the reason is, so I'm seeking your assistance."
![image](https://github.com/MCZhi/Driving-IRL-NGSIM/assets/143694720/eed428d7-6f2b-4f16-8e24-75dfd620cd59)

**Comment by MCZhi** [comment]
I don't exactly know the reason, but I strongly suggest using the code in a Linux environment since I have only tested it in Linux.

**Comment by 123yu456** [comment]
thanks a lot! By the way, can you tell me the version of python? is the version of python 3.7 ok?

**Comment by MCZhi** [comment]
Yes, Python 3.7 would work.

**Comment by 123yu456** [comment]
Thanks again! When I read codes, I found that in "behavior.py" and "control.py", except the IDM and MOBIL models, there are many formulas and parameters you do not mentioned in your paper, I wonder what they are basing it on .Is there any relevant references paper or books you can provide me? Thanks a lot!

**Comment by 123yu456** [comment]
Sorry to bother you again. May I ask how long it usually takes to see the visualization results after running personal_IRL? I have been running it for over twelve hours and still haven't seen any results.
![image](https://github.com/MCZhi/Driving-IRL-NGSIM/assets/143694720/b589a03b-ab46-4ee2-8627-00d0b2ce9d0e)

**Comment by MCZhi** [comment]
If you want to visualize the testing results, set the parameter `render_env = True` at the beginning of the code.
